### ISSUE TITLE
Content-Length problems

### ISSUE THREAD

**Issue by towhans** [tailhook/libwebsite#6]
In HTTP/1.1 it says:

The field value MAY be preceded by any amount of LWS, though a single SP is preferred. 

libwebsite always puts more spaces in front of the value like:

Content-Length:&nbsp;&nbsp;&nbsp;&nbsp;9550

Which causes problems to clients that don't adhere to HTTP/1.1 specification and only accept exactly one SP. One such client is Tsung testing framework. It can only handle one SP.

This is really Tsungs issue.

**Comment by tailhook** [comment]
Yes, it's Tsung issue. I may consider change this if I would do rewrite the library. But for now it's too complex to change. (When the header is inserted into buffer, content length is yet unknown, so we reserve space for it and fill it later, this allows to do less memory allocations)

**Comment by towhans** [comment]
FYI: I reported the bug to Tsung and they fixed it: https://support.process-one.net/browse/TSUN-238?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

So it is now possible to benchmark zerogw by Tsung.

**Comment by tailhook** [comment]
Great news. Thanks!
